reorder_imports = true
use_field_init_shorthand = true
array_width = 80
condense_wildcard_suffixes = true
edition = "2024"
enum_discrim_align_threshold = 20
imports_granularity = "Crate"
unstable_features = true
group_imports = "StdExternalCrate"
use_small_heuristics = "Max"
max_width = 80
brace_style = "PreferSameLine"
